/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace FlexibleTieredStaking {
  export type ArweaveFileStruct = {
    txId: string;
    fileType: string;
    description: string;
    version: BigNumberish;
    timestamp: BigNumberish;
  };

  export type ArweaveFileStructOutput = [
    txId: string,
    fileType: string,
    description: string,
    version: bigint,
    timestamp: bigint
  ] & {
    txId: string;
    fileType: string;
    description: string;
    version: bigint;
    timestamp: bigint;
  };
}

export interface FlexibleTieredStakingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "FILE_MANAGER_ROLE"
      | "GRACE_PERIOD"
      | "MAX_USERS_PER_CLEAR"
      | "MIN_STAKING_DURATION"
      | "WETH"
      | "addFileToTierBatch"
      | "addFileToUserBatch"
      | "addTier"
      | "allowance"
      | "backupPriceOracle"
      | "deployToYield"
      | "emergencyWithdraw"
      | "emergencyWithdrawFromYield"
      | "firstStakeTimestamp"
      | "gasRefundReward"
      | "getContractBalances"
      | "getContractStatus"
      | "getOracleInfo"
      | "getRoleAdmin"
      | "getTier"
      | "getTierCount"
      | "getTierFiles"
      | "getTotalStaked"
      | "getUserFiles"
      | "getUserStakingInfo"
      | "getUserTier"
      | "getYieldInfo"
      | "grantRole"
      | "hasAccess"
      | "hasRole"
      | "lastUnstakeTimestamp"
      | "logFileAccess"
      | "maxYieldDeploymentBps"
      | "meetsTierRequirement"
      | "owner"
      | "pause"
      | "paused"
      | "primaryPriceOracle"
      | "removeTier"
      | "renounceOwnership"
      | "renounceRole"
      | "revokeRole"
      | "setBackupPriceOracle"
      | "setGasRefundReward"
      | "setMaxYieldDeployment"
      | "setPrimaryPriceOracle"
      | "setStakingToken"
      | "setUniswapPair"
      | "setYieldDeployedShares"
      | "setYieldEnabled"
      | "setYieldStrategy"
      | "stake"
      | "stakeBatch"
      | "stakeTimestamp"
      | "stakingToken"
      | "supportsInterface"
      | "tiers"
      | "transferOwnership"
      | "uniswapPair"
      | "unpause"
      | "unstake"
      | "unstakeBatch"
      | "updateTier"
      | "userStakedTokens"
      | "verifyStaker"
      | "withdrawETH"
      | "withdrawFromYield"
      | "yieldDeployedShares"
      | "yieldEnabled"
      | "yieldStrategy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FileAccessLogged"
      | "GasRefundRewardSet"
      | "MaxYieldDeploymentUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Staked"
      | "TierAdded"
      | "TierFileAdded"
      | "TierModified"
      | "TierRemoved"
      | "TierUpdated"
      | "UniswapPairSet"
      | "Unpaused"
      | "Unstaked"
      | "UserFileAdded"
      | "YieldDeposited"
      | "YieldEnabled"
      | "YieldSharesAdjusted"
      | "YieldStrategySet"
      | "YieldWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FILE_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GRACE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_USERS_PER_CLEAR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_STAKING_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addFileToTierBatch",
    values: [BigNumberish, string[], string[], string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addFileToUserBatch",
    values: [AddressLike, string[], string[], string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addTier",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "backupPriceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployToYield",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawFromYield",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "firstStakeTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gasRefundReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalances",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOracleInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTierCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTierFiles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserFiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStakingInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getYieldInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastUnstakeTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logFileAccess",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "maxYieldDeploymentBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "meetsTierRequirement",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "primaryPriceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBackupPriceOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGasRefundReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxYieldDeployment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrimaryPriceOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakingToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUniswapPair",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setYieldDeployedShares",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setYieldEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setYieldStrategy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "stakeBatch",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "tiers", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapPair",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeBatch",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTier",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "userStakedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyStaker",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFromYield",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldDeployedShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "yieldEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "yieldStrategy",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FILE_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GRACE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_USERS_PER_CLEAR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_STAKING_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addFileToTierBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addFileToUserBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addTier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "backupPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployToYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawFromYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "firstStakeTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gasRefundReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOracleInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTierCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTierFiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserFiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStakingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYieldInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastUnstakeTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logFileAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxYieldDeploymentBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "meetsTierRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "primaryPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removeTier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBackupPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasRefundReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxYieldDeployment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPrimaryPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUniswapPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setYieldDeployedShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setYieldEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setYieldStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeBatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tiers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unstakeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateTier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userStakedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyStaker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldDeployedShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldStrategy",
    data: BytesLike
  ): Result;
}

export namespace FileAccessLoggedEvent {
  export type InputTuple = [
    user: AddressLike,
    tierIndex: BigNumberish,
    txId: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tierIndex: bigint,
    txId: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    tierIndex: bigint;
    txId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasRefundRewardSetEvent {
  export type InputTuple = [gasRefundReward: BigNumberish];
  export type OutputTuple = [gasRefundReward: bigint];
  export interface OutputObject {
    gasRefundReward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxYieldDeploymentUpdatedEvent {
  export type InputTuple = [newMaxBps: BigNumberish];
  export type OutputTuple = [newMaxBps: bigint];
  export interface OutputObject {
    newMaxBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TierAddedEvent {
  export type InputTuple = [
    tierIndex: BigNumberish,
    threshold: BigNumberish,
    name: string
  ];
  export type OutputTuple = [
    tierIndex: bigint,
    threshold: bigint,
    name: string
  ];
  export interface OutputObject {
    tierIndex: bigint;
    threshold: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TierFileAddedEvent {
  export type InputTuple = [
    tierIndex: BigNumberish,
    txId: string,
    fileType: string,
    description: string,
    version: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tierIndex: bigint,
    txId: string,
    fileType: string,
    description: string,
    version: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    tierIndex: bigint;
    txId: string;
    fileType: string;
    description: string;
    version: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TierModifiedEvent {
  export type InputTuple = [
    tierIndex: BigNumberish,
    newThreshold: BigNumberish,
    newName: string
  ];
  export type OutputTuple = [
    tierIndex: bigint,
    newThreshold: bigint,
    newName: string
  ];
  export interface OutputObject {
    tierIndex: bigint;
    newThreshold: bigint;
    newName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TierRemovedEvent {
  export type InputTuple = [tierIndex: BigNumberish];
  export type OutputTuple = [tierIndex: bigint];
  export interface OutputObject {
    tierIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TierUpdatedEvent {
  export type InputTuple = [user: AddressLike, tierIndex: BigNumberish];
  export type OutputTuple = [user: string, tierIndex: bigint];
  export interface OutputObject {
    user: string;
    tierIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UniswapPairSetEvent {
  export type InputTuple = [pairAddress: AddressLike];
  export type OutputTuple = [pairAddress: string];
  export interface OutputObject {
    pairAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserFileAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    txId: string,
    fileType: string,
    description: string,
    version: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    txId: string,
    fileType: string,
    description: string,
    version: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    txId: string;
    fileType: string;
    description: string;
    version: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldDepositedEvent {
  export type InputTuple = [amount: BigNumberish, shares: BigNumberish];
  export type OutputTuple = [amount: bigint, shares: bigint];
  export interface OutputObject {
    amount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldEnabledEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldSharesAdjustedEvent {
  export type InputTuple = [oldShares: BigNumberish, newShares: BigNumberish];
  export type OutputTuple = [oldShares: bigint, newShares: bigint];
  export interface OutputObject {
    oldShares: bigint;
    newShares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldStrategySetEvent {
  export type InputTuple = [strategy: AddressLike];
  export type OutputTuple = [strategy: string];
  export interface OutputObject {
    strategy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldWithdrawnEvent {
  export type InputTuple = [shares: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [shares: bigint, amount: bigint];
  export interface OutputObject {
    shares: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FlexibleTieredStaking extends BaseContract {
  connect(runner?: ContractRunner | null): FlexibleTieredStaking;
  waitForDeployment(): Promise<this>;

  interface: FlexibleTieredStakingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  FILE_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  GRACE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MAX_USERS_PER_CLEAR: TypedContractMethod<[], [bigint], "view">;

  MIN_STAKING_DURATION: TypedContractMethod<[], [bigint], "view">;

  WETH: TypedContractMethod<[], [string], "view">;

  addFileToTierBatch: TypedContractMethod<
    [
      tierIndex: BigNumberish,
      txIds: string[],
      fileTypes: string[],
      descriptions: string[],
      versions: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  addFileToUserBatch: TypedContractMethod<
    [
      user: AddressLike,
      txIds: string[],
      fileTypes: string[],
      descriptions: string[],
      versions: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  addTier: TypedContractMethod<
    [threshold: BigNumberish, name: string],
    [void],
    "nonpayable"
  >;

  allowance: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  backupPriceOracle: TypedContractMethod<[], [string], "view">;

  deployToYield: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  emergencyWithdrawFromYield: TypedContractMethod<[], [void], "nonpayable">;

  firstStakeTimestamp: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  gasRefundReward: TypedContractMethod<[], [bigint], "view">;

  getContractBalances: TypedContractMethod<
    [],
    [[bigint, bigint] & { ethBalance: bigint; tokenBalance: bigint }],
    "view"
  >;

  getContractStatus: TypedContractMethod<
    [],
    [
      [boolean, boolean, boolean, boolean, bigint] & {
        isPaused: boolean;
        stakingTokenSet: boolean;
        primaryOracleSet: boolean;
        backupOracleSet: boolean;
        tierCount: bigint;
      }
    ],
    "view"
  >;

  getOracleInfo: TypedContractMethod<
    [],
    [
      [string, string, bigint, string] & {
        primaryOracle: string;
        backupOracle: string;
        currentGasRefundReward: bigint;
        pairAddress: string;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTier: TypedContractMethod<
    [tierIndex: BigNumberish],
    [[bigint, string] & { threshold: bigint; name: string }],
    "view"
  >;

  getTierCount: TypedContractMethod<[], [bigint], "view">;

  getTierFiles: TypedContractMethod<
    [tierIndex: BigNumberish],
    [FlexibleTieredStaking.ArweaveFileStructOutput[]],
    "view"
  >;

  getTotalStaked: TypedContractMethod<[], [bigint], "view">;

  getUserFiles: TypedContractMethod<
    [user: AddressLike],
    [FlexibleTieredStaking.ArweaveFileStructOutput[]],
    "view"
  >;

  getUserStakingInfo: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, boolean, boolean] & {
        stakedAmount: bigint;
        usdValue: bigint;
        userHasAccess: boolean;
        canUnstake: boolean;
      }
    ],
    "view"
  >;

  getUserTier: TypedContractMethod<
    [user: AddressLike],
    [[bigint, string] & { tierIndex: bigint; tierName: string }],
    "view"
  >;

  getYieldInfo: TypedContractMethod<
    [],
    [
      [string, bigint, bigint, bigint, boolean] & {
        strategyAddress: string;
        deployedShares: bigint;
        totalValue: bigint;
        apyBps: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasAccess: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  lastUnstakeTimestamp: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  logFileAccess: TypedContractMethod<
    [user: AddressLike, tierIndex: BigNumberish, txId: string],
    [void],
    "nonpayable"
  >;

  maxYieldDeploymentBps: TypedContractMethod<[], [bigint], "view">;

  meetsTierRequirement: TypedContractMethod<
    [user: AddressLike, tierIndex: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  primaryPriceOracle: TypedContractMethod<[], [string], "view">;

  removeTier: TypedContractMethod<
    [tierIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setBackupPriceOracle: TypedContractMethod<
    [_backupPriceOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setGasRefundReward: TypedContractMethod<
    [_gasRefundReward: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxYieldDeployment: TypedContractMethod<
    [_maxBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPrimaryPriceOracle: TypedContractMethod<
    [_primaryPriceOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setStakingToken: TypedContractMethod<
    [_stakingToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setUniswapPair: TypedContractMethod<
    [_uniswapPair: AddressLike],
    [void],
    "nonpayable"
  >;

  setYieldDeployedShares: TypedContractMethod<
    [newShares: BigNumberish],
    [void],
    "nonpayable"
  >;

  setYieldEnabled: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  setYieldStrategy: TypedContractMethod<
    [_strategy: AddressLike],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  stakeBatch: TypedContractMethod<
    [amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  stakeTimestamp: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  stakingToken: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  tiers: TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, string] & { threshold: bigint; name: string }],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uniswapPair: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  unstake: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  unstakeBatch: TypedContractMethod<
    [amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  updateTier: TypedContractMethod<
    [tierIndex: BigNumberish, newThreshold: BigNumberish, newName: string],
    [void],
    "nonpayable"
  >;

  userStakedTokens: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  verifyStaker: TypedContractMethod<
    [user: AddressLike, tierIndex: BigNumberish],
    [boolean],
    "view"
  >;

  withdrawETH: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawFromYield: TypedContractMethod<
    [shares: BigNumberish],
    [void],
    "nonpayable"
  >;

  yieldDeployedShares: TypedContractMethod<[], [bigint], "view">;

  yieldEnabled: TypedContractMethod<[], [boolean], "view">;

  yieldStrategy: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FILE_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GRACE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_USERS_PER_CLEAR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STAKING_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WETH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addFileToTierBatch"
  ): TypedContractMethod<
    [
      tierIndex: BigNumberish,
      txIds: string[],
      fileTypes: string[],
      descriptions: string[],
      versions: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addFileToUserBatch"
  ): TypedContractMethod<
    [
      user: AddressLike,
      txIds: string[],
      fileTypes: string[],
      descriptions: string[],
      versions: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addTier"
  ): TypedContractMethod<
    [threshold: BigNumberish, name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "backupPriceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deployToYield"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdrawFromYield"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "firstStakeTimestamp"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "gasRefundReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContractBalances"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { ethBalance: bigint; tokenBalance: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractStatus"
  ): TypedContractMethod<
    [],
    [
      [boolean, boolean, boolean, boolean, bigint] & {
        isPaused: boolean;
        stakingTokenSet: boolean;
        primaryOracleSet: boolean;
        backupOracleSet: boolean;
        tierCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOracleInfo"
  ): TypedContractMethod<
    [],
    [
      [string, string, bigint, string] & {
        primaryOracle: string;
        backupOracle: string;
        currentGasRefundReward: bigint;
        pairAddress: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTier"
  ): TypedContractMethod<
    [tierIndex: BigNumberish],
    [[bigint, string] & { threshold: bigint; name: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTierCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTierFiles"
  ): TypedContractMethod<
    [tierIndex: BigNumberish],
    [FlexibleTieredStaking.ArweaveFileStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserFiles"
  ): TypedContractMethod<
    [user: AddressLike],
    [FlexibleTieredStaking.ArweaveFileStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserStakingInfo"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, boolean, boolean] & {
        stakedAmount: bigint;
        usdValue: bigint;
        userHasAccess: boolean;
        canUnstake: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTier"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint, string] & { tierIndex: bigint; tierName: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getYieldInfo"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, bigint, bigint, boolean] & {
        strategyAddress: string;
        deployedShares: bigint;
        totalValue: bigint;
        apyBps: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastUnstakeTimestamp"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "logFileAccess"
  ): TypedContractMethod<
    [user: AddressLike, tierIndex: BigNumberish, txId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "maxYieldDeploymentBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "meetsTierRequirement"
  ): TypedContractMethod<
    [user: AddressLike, tierIndex: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "primaryPriceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeTier"
  ): TypedContractMethod<[tierIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBackupPriceOracle"
  ): TypedContractMethod<
    [_backupPriceOracle: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGasRefundReward"
  ): TypedContractMethod<
    [_gasRefundReward: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxYieldDeployment"
  ): TypedContractMethod<[_maxBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPrimaryPriceOracle"
  ): TypedContractMethod<
    [_primaryPriceOracle: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setStakingToken"
  ): TypedContractMethod<[_stakingToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUniswapPair"
  ): TypedContractMethod<[_uniswapPair: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setYieldDeployedShares"
  ): TypedContractMethod<[newShares: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setYieldEnabled"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setYieldStrategy"
  ): TypedContractMethod<[_strategy: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeBatch"
  ): TypedContractMethod<[amounts: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeTimestamp"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakingToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tiers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, string] & { threshold: bigint; name: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uniswapPair"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstakeBatch"
  ): TypedContractMethod<[amounts: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTier"
  ): TypedContractMethod<
    [tierIndex: BigNumberish, newThreshold: BigNumberish, newName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userStakedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyStaker"
  ): TypedContractMethod<
    [user: AddressLike, tierIndex: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawETH"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFromYield"
  ): TypedContractMethod<[shares: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "yieldDeployedShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yieldEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "yieldStrategy"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FileAccessLogged"
  ): TypedContractEvent<
    FileAccessLoggedEvent.InputTuple,
    FileAccessLoggedEvent.OutputTuple,
    FileAccessLoggedEvent.OutputObject
  >;
  getEvent(
    key: "GasRefundRewardSet"
  ): TypedContractEvent<
    GasRefundRewardSetEvent.InputTuple,
    GasRefundRewardSetEvent.OutputTuple,
    GasRefundRewardSetEvent.OutputObject
  >;
  getEvent(
    key: "MaxYieldDeploymentUpdated"
  ): TypedContractEvent<
    MaxYieldDeploymentUpdatedEvent.InputTuple,
    MaxYieldDeploymentUpdatedEvent.OutputTuple,
    MaxYieldDeploymentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "TierAdded"
  ): TypedContractEvent<
    TierAddedEvent.InputTuple,
    TierAddedEvent.OutputTuple,
    TierAddedEvent.OutputObject
  >;
  getEvent(
    key: "TierFileAdded"
  ): TypedContractEvent<
    TierFileAddedEvent.InputTuple,
    TierFileAddedEvent.OutputTuple,
    TierFileAddedEvent.OutputObject
  >;
  getEvent(
    key: "TierModified"
  ): TypedContractEvent<
    TierModifiedEvent.InputTuple,
    TierModifiedEvent.OutputTuple,
    TierModifiedEvent.OutputObject
  >;
  getEvent(
    key: "TierRemoved"
  ): TypedContractEvent<
    TierRemovedEvent.InputTuple,
    TierRemovedEvent.OutputTuple,
    TierRemovedEvent.OutputObject
  >;
  getEvent(
    key: "TierUpdated"
  ): TypedContractEvent<
    TierUpdatedEvent.InputTuple,
    TierUpdatedEvent.OutputTuple,
    TierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UniswapPairSet"
  ): TypedContractEvent<
    UniswapPairSetEvent.InputTuple,
    UniswapPairSetEvent.OutputTuple,
    UniswapPairSetEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;
  getEvent(
    key: "UserFileAdded"
  ): TypedContractEvent<
    UserFileAddedEvent.InputTuple,
    UserFileAddedEvent.OutputTuple,
    UserFileAddedEvent.OutputObject
  >;
  getEvent(
    key: "YieldDeposited"
  ): TypedContractEvent<
    YieldDepositedEvent.InputTuple,
    YieldDepositedEvent.OutputTuple,
    YieldDepositedEvent.OutputObject
  >;
  getEvent(
    key: "YieldEnabled"
  ): TypedContractEvent<
    YieldEnabledEvent.InputTuple,
    YieldEnabledEvent.OutputTuple,
    YieldEnabledEvent.OutputObject
  >;
  getEvent(
    key: "YieldSharesAdjusted"
  ): TypedContractEvent<
    YieldSharesAdjustedEvent.InputTuple,
    YieldSharesAdjustedEvent.OutputTuple,
    YieldSharesAdjustedEvent.OutputObject
  >;
  getEvent(
    key: "YieldStrategySet"
  ): TypedContractEvent<
    YieldStrategySetEvent.InputTuple,
    YieldStrategySetEvent.OutputTuple,
    YieldStrategySetEvent.OutputObject
  >;
  getEvent(
    key: "YieldWithdrawn"
  ): TypedContractEvent<
    YieldWithdrawnEvent.InputTuple,
    YieldWithdrawnEvent.OutputTuple,
    YieldWithdrawnEvent.OutputObject
  >;

  filters: {
    "FileAccessLogged(address,uint256,string,uint256)": TypedContractEvent<
      FileAccessLoggedEvent.InputTuple,
      FileAccessLoggedEvent.OutputTuple,
      FileAccessLoggedEvent.OutputObject
    >;
    FileAccessLogged: TypedContractEvent<
      FileAccessLoggedEvent.InputTuple,
      FileAccessLoggedEvent.OutputTuple,
      FileAccessLoggedEvent.OutputObject
    >;

    "GasRefundRewardSet(uint256)": TypedContractEvent<
      GasRefundRewardSetEvent.InputTuple,
      GasRefundRewardSetEvent.OutputTuple,
      GasRefundRewardSetEvent.OutputObject
    >;
    GasRefundRewardSet: TypedContractEvent<
      GasRefundRewardSetEvent.InputTuple,
      GasRefundRewardSetEvent.OutputTuple,
      GasRefundRewardSetEvent.OutputObject
    >;

    "MaxYieldDeploymentUpdated(uint256)": TypedContractEvent<
      MaxYieldDeploymentUpdatedEvent.InputTuple,
      MaxYieldDeploymentUpdatedEvent.OutputTuple,
      MaxYieldDeploymentUpdatedEvent.OutputObject
    >;
    MaxYieldDeploymentUpdated: TypedContractEvent<
      MaxYieldDeploymentUpdatedEvent.InputTuple,
      MaxYieldDeploymentUpdatedEvent.OutputTuple,
      MaxYieldDeploymentUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Staked(address,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "TierAdded(uint256,uint256,string)": TypedContractEvent<
      TierAddedEvent.InputTuple,
      TierAddedEvent.OutputTuple,
      TierAddedEvent.OutputObject
    >;
    TierAdded: TypedContractEvent<
      TierAddedEvent.InputTuple,
      TierAddedEvent.OutputTuple,
      TierAddedEvent.OutputObject
    >;

    "TierFileAdded(uint256,string,string,string,uint256,uint256)": TypedContractEvent<
      TierFileAddedEvent.InputTuple,
      TierFileAddedEvent.OutputTuple,
      TierFileAddedEvent.OutputObject
    >;
    TierFileAdded: TypedContractEvent<
      TierFileAddedEvent.InputTuple,
      TierFileAddedEvent.OutputTuple,
      TierFileAddedEvent.OutputObject
    >;

    "TierModified(uint256,uint256,string)": TypedContractEvent<
      TierModifiedEvent.InputTuple,
      TierModifiedEvent.OutputTuple,
      TierModifiedEvent.OutputObject
    >;
    TierModified: TypedContractEvent<
      TierModifiedEvent.InputTuple,
      TierModifiedEvent.OutputTuple,
      TierModifiedEvent.OutputObject
    >;

    "TierRemoved(uint256)": TypedContractEvent<
      TierRemovedEvent.InputTuple,
      TierRemovedEvent.OutputTuple,
      TierRemovedEvent.OutputObject
    >;
    TierRemoved: TypedContractEvent<
      TierRemovedEvent.InputTuple,
      TierRemovedEvent.OutputTuple,
      TierRemovedEvent.OutputObject
    >;

    "TierUpdated(address,uint256)": TypedContractEvent<
      TierUpdatedEvent.InputTuple,
      TierUpdatedEvent.OutputTuple,
      TierUpdatedEvent.OutputObject
    >;
    TierUpdated: TypedContractEvent<
      TierUpdatedEvent.InputTuple,
      TierUpdatedEvent.OutputTuple,
      TierUpdatedEvent.OutputObject
    >;

    "UniswapPairSet(address)": TypedContractEvent<
      UniswapPairSetEvent.InputTuple,
      UniswapPairSetEvent.OutputTuple,
      UniswapPairSetEvent.OutputObject
    >;
    UniswapPairSet: TypedContractEvent<
      UniswapPairSetEvent.InputTuple,
      UniswapPairSetEvent.OutputTuple,
      UniswapPairSetEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Unstaked(address,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;

    "UserFileAdded(address,string,string,string,uint256,uint256)": TypedContractEvent<
      UserFileAddedEvent.InputTuple,
      UserFileAddedEvent.OutputTuple,
      UserFileAddedEvent.OutputObject
    >;
    UserFileAdded: TypedContractEvent<
      UserFileAddedEvent.InputTuple,
      UserFileAddedEvent.OutputTuple,
      UserFileAddedEvent.OutputObject
    >;

    "YieldDeposited(uint256,uint256)": TypedContractEvent<
      YieldDepositedEvent.InputTuple,
      YieldDepositedEvent.OutputTuple,
      YieldDepositedEvent.OutputObject
    >;
    YieldDeposited: TypedContractEvent<
      YieldDepositedEvent.InputTuple,
      YieldDepositedEvent.OutputTuple,
      YieldDepositedEvent.OutputObject
    >;

    "YieldEnabled(bool)": TypedContractEvent<
      YieldEnabledEvent.InputTuple,
      YieldEnabledEvent.OutputTuple,
      YieldEnabledEvent.OutputObject
    >;
    YieldEnabled: TypedContractEvent<
      YieldEnabledEvent.InputTuple,
      YieldEnabledEvent.OutputTuple,
      YieldEnabledEvent.OutputObject
    >;

    "YieldSharesAdjusted(uint256,uint256)": TypedContractEvent<
      YieldSharesAdjustedEvent.InputTuple,
      YieldSharesAdjustedEvent.OutputTuple,
      YieldSharesAdjustedEvent.OutputObject
    >;
    YieldSharesAdjusted: TypedContractEvent<
      YieldSharesAdjustedEvent.InputTuple,
      YieldSharesAdjustedEvent.OutputTuple,
      YieldSharesAdjustedEvent.OutputObject
    >;

    "YieldStrategySet(address)": TypedContractEvent<
      YieldStrategySetEvent.InputTuple,
      YieldStrategySetEvent.OutputTuple,
      YieldStrategySetEvent.OutputObject
    >;
    YieldStrategySet: TypedContractEvent<
      YieldStrategySetEvent.InputTuple,
      YieldStrategySetEvent.OutputTuple,
      YieldStrategySetEvent.OutputObject
    >;

    "YieldWithdrawn(uint256,uint256)": TypedContractEvent<
      YieldWithdrawnEvent.InputTuple,
      YieldWithdrawnEvent.OutputTuple,
      YieldWithdrawnEvent.OutputObject
    >;
    YieldWithdrawn: TypedContractEvent<
      YieldWithdrawnEvent.InputTuple,
      YieldWithdrawnEvent.OutputTuple,
      YieldWithdrawnEvent.OutputObject
    >;
  };
}
